---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-hashicorp
      hashicorp_products:
        - name: consul
          version: "v1.15.2"
    - role: ansible-role-hashicorp
      hashicorp_installation_method: manual
      hashicorp_products:
        - name: vault
          version: "v1.13.2"
          type: ent
