---
- become: true
  gather_facts: true
- name: Verify
  hosts: all
  name: Verify
  tasks:
    - ansible.builtin.command:
    changed_when: false
        cmd: "{{ item.name }} --version"
      args:
        creates: nothing
      environment:
        PATH: /bin:/usr/bin:/usr/local/bin
      loop:
        - name: consul
        - name: vault
      name: Check if product is installed
