---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Check if product is installed
      ansible.builtin.command:
        cmd: "{{ item.name }} --version"
        creates: nothing
      environment:
        PATH: /bin:/usr/bin:/usr/local/bin
      loop:
        - name: consul
        - name: vault
      changed_when: false
